### ISSUE TITLE
[Suggestion] Voices of wynn

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Rafii2198/WynnicEnchantments#1]
Not sure if you knew about it but there's a mod called "Voices of wynn" that adds voices to all the npc in the server

**Comment by Rafii2198** [comment]
Thanks for the suggestion! 😃
I am well aware of the VoW mod, but I can only include mods that are on Modrinth. VoW is also too big to be inside a modpack in my opinion, so even if I could add it, I probably wouldn't do it. But I am thinking about adding another section to the description, mentioning usful mods that can't be added, and Voices of Wynn is one of them!

**Comment by Aces-and-Jacks** [comment]
ah, ok then. I saw other modpacks on modrinth embed mods that are on curseforge so I wasn't sure if it was possible or not

**Comment by Rafii2198** [comment]
It is possible, I just want to have the purest Modrinth modpack possible, also Modrinth has I believe 200 MB file size limit and the size of Voices of Wynn is over 500 MB, over double of that 💀

**Comment by Aces-and-Jacks** [comment]
ah, ok then. Well it is a long download for voices of wynn and I thought the redistribution thing may be something to check but wasn't sure about that. Great modpack tho 💯

**Comment by Rafii2198** [comment]
Thank you so much! It really means so much to me 🥺
