### ISSUE TITLE
Update the mods in the pack

### ISSUE THREAD

**Issue by drakosoldier298** [Rafii2198/WynnicEnchantments#6]
there are quite a few mods out of date, mainly wynntils which cause the pack to be near useless.

**Comment by Rafii2198** [comment]
Update Wynntil on your own. Wynntils gets multiple updates per day, it should be on the user to keep their Wynntils updated since it takes 1 press of a button to update it. If I were to update the pack with each Wynntils update, I literally would not have time for anything else during my day.
