### ISSUE TITLE
Crash on Joining the server

### ISSUE THREAD

**Issue by Nxman** [Rafii2198/WynnicEnchantments#7]
heres the log :
 https://paste.atlauncher.com/view/52656a73-fdab-4709-a572-297ae0aeb31f
launcher is Atlauncher and did a full delete of instance and installation but the problem still persists
also tried launching on prisim launcher, still the same 
Version 0.6.4 of the modpack

**Comment by Rafii2198** [comment]
Do you have a crash log? It should contain more information. I personally have no issues at all on fresh installs

**Comment by Nxman** [comment]
This is the log i hope it helps u fix tbe problem and i would try to provide any info if needed

**Comment by Nxman** [comment]
[Uploading crash-2023-12-08_01.00.56-client.txt…]()

**Comment by Nxman** [comment]
[crash-2023-12-08_01.00.56-client.txt](https://github.com/Rafii2198/WynnicEnchantments/files/13606235/crash-2023-12-08_01.00.56-client.txt)

**Comment by Rafii2198** [comment]
Can you try disabling the mod called Flow?

**Comment by Nxman** [comment]
On it

**Comment by Nxman** [comment]
hey sorry for the delay it was 3 am and i had to sleep 
the mod flow works perfectly on its own without any other mods so i think it is a mod interaction

**Comment by Rafii2198** [comment]
Hmm, ok so if you want you can search for the mod that causes it to crash and if you find it you can report it to Flow dev. If you want of course, I would do it if I could, as I said everything works perfectly on my end, so I can test that.

**Comment by Rafii2198** [comment]
@Nxman Hey, could you try disabling Dynamic FPS and seeing if that works?

**Comment by TeamBattino** [comment]
> Can you try disabling the mod called Flow?

I'm experiencing the same issue, and disabling this mod fixed it. Disabling Dynamic FPS still causes the crash.

**Comment by Rafii2198** [comment]
Hmm, I wanted to find which mod causes Flow to crash but I have no clue and thus can't report it

**Comment by TeamBattino** [comment]
Do you know of some sort of debugging tool/mod I could use to get some more insight?

**Comment by Rafii2198** [comment]
I don't know any that would help this case, best would be trying to do binary search, but as I do not experiance such issue, I can't test it

**Comment by TeamBattino** [comment]
How do you do binary search without accidentally removing dependencies?

**Comment by TeamBattino** [comment]
Ive done binary search and ive found its flow+wynntils that causes the issue
<img width="466" alt="image" src="https://github.com/Rafii2198/WynnicEnchantments/assets/60046498/29cc9b1c-f092-4779-a7b9-5b7e731499ac">

**Comment by TeamBattino** [comment]
👍 [Flow issue](https://github.com/IMB11/Flow/issues/16)
